// =============================================================================
// EVENMIA - Questionnaires exhaustifs par type d'événement
// Généré le 2026-04-11
// =============================================================================
// Légende:
//   impactsPricing: true = cette réponse influence le devis
//   priority: "essential" | "nice-to-have"
//   conditionalOn: null | "id de la question parente"
//   phase: "avant" | "jour-j" | "apres"
// =============================================================================

export interface Question {
  id: string;
  text: string;
  type: "text" | "number" | "select" | "multiselect" | "date" | "boolean" | "textarea" | "time" | "range";
  options?: string[];
  impactsPricing: boolean;
  pricingNote?: string;
  priority: "essential" | "nice-to-have";
  conditionalOn?: string | null;
  phase: "avant" | "jour-j" | "apres";
}

export interface EventQuestionnaire {
  eventType: string;
  questions: Question[];
}

// =============================================================================
// 1. MARIAGE (Wedding)
// =============================================================================
export const MARIAGE_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "mar-001",
    text: "Quelle est la date souhaitée pour le mariage ?",
    type: "date",
    impactsPricing: true,
    pricingNote: "Haute saison (juin-sept) = tarifs majorés de 20-40%",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-002",
    text: "Avez-vous une date de repli si la première n'est pas disponible ?",
    type: "date",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-003",
    text: "Quel est le type de cérémonie ? (civile, religieuse, laïque, symbolique, mixte)",
    type: "select",
    options: ["Civile uniquement", "Religieuse + civile", "Laïque + civile", "Symbolique", "Mixte (plusieurs rites)"],
    impactsPricing: true,
    pricingNote: "Cérémonie laïque = officiant + décor supplémentaire. Religieuse = coordination avec le lieu de culte",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-004",
    text: "Si cérémonie religieuse, quelle confession ? (catholique, protestante, juive, musulmane, hindoue, autre)",
    type: "select",
    options: ["Catholique", "Protestante", "Juive", "Musulmane", "Hindoue", "Bouddhiste", "Autre"],
    impactsPricing: true,
    pricingNote: "Chaque rite a ses exigences spécifiques (dais, houppa, mandap, etc.)",
    priority: "essential",
    conditionalOn: "mar-003",
    phase: "avant",
  },
  {
    id: "mar-005",
    text: "Combien d'invités prévoyez-vous ? (fourchette)",
    type: "range",
    impactsPricing: true,
    pricingNote: "Impact direct sur traiteur, lieu, boissons, vaisselle, mobilier, plan de table",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-006",
    text: "Quel est votre budget global estimé ?",
    type: "select",
    options: ["Moins de 5 000€", "5 000-10 000€", "10 000-20 000€", "20 000-40 000€", "40 000-70 000€", "70 000-100 000€", "Plus de 100 000€"],
    impactsPricing: true,
    pricingNote: "Détermine le niveau de prestation global",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-007",
    text: "Avez-vous déjà réservé un lieu pour la réception ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Si non, recherche de lieu = prestation supplémentaire",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-008",
    text: "Quel type de lieu souhaitez-vous ? (château, domaine, salle, plein air, plage, restaurant, grange, jardin, rooftop, bateau)",
    type: "multiselect",
    options: ["Château", "Domaine viticole", "Salle de réception", "Plein air", "Plage", "Restaurant gastronomique", "Grange/ferme", "Jardin privé", "Rooftop", "Bateau/péniche", "Hôtel", "Mairie uniquement", "Lieu insolite"],
    impactsPricing: true,
    pricingNote: "Le lieu représente 30-50% du budget total",
    priority: "essential",
    conditionalOn: "mar-007",
    phase: "avant",
  },
  {
    id: "mar-009",
    text: "Souhaitez-vous que la cérémonie et la réception soient au même endroit ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Deux lieux = transport invités + logistique supplémentaire",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-010",
    text: "Avez-vous besoin d'un plan B en cas de pluie (si extérieur) ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Location de tente/chapiteau ou salle de repli",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-011",
    text: "Quel type de repas souhaitez-vous ? (assis, buffet, cocktail dinatoire, food trucks, brunch)",
    type: "select",
    options: ["Repas assis servi à table", "Buffet", "Cocktail dînatoire", "Food trucks", "Brunch", "Mixte (cocktail + assis)", "Barbecue/méchoui"],
    impactsPricing: true,
    pricingNote: "Repas assis = 80-200€/pers, cocktail = 50-120€/pers, buffet = 60-150€/pers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-012",
    text: "Combien de pièces cocktail et quels plats pour le menu ? (entrée, plat, fromage, dessert)",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Nombre de pièces cocktail et nombre de plats = prix traiteur",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-013",
    text: "Y a-t-il des régimes alimentaires spéciaux parmi les invités ? (végétarien, vegan, halal, casher, sans gluten, allergies)",
    type: "multiselect",
    options: ["Végétarien", "Végan", "Halal", "Casher", "Sans gluten", "Sans lactose", "Allergies aux fruits à coque", "Allergies aux crustacés", "Autre"],
    impactsPricing: true,
    pricingNote: "Menus spéciaux = surcoût traiteur",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-014",
    text: "Souhaitez-vous un vin d'honneur / cocktail avant le repas ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Cocktail = 15-40€/pers selon les pièces",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-015",
    text: "Quelle formule boissons ? (open bar, boissons limitées, soft uniquement, BYOB)",
    type: "select",
    options: ["Open bar toute la soirée", "Open bar limité (3-4h)", "Boissons au repas uniquement", "Soft bar uniquement", "Les invités apportent (BYOB)", "Mixte"],
    impactsPricing: true,
    pricingNote: "Open bar = 30-80€/pers, un des postes les plus variables",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-016",
    text: "Souhaitez-vous un gâteau de mariage / pièce montée ? Quel type ?",
    type: "select",
    options: ["Pièce montée traditionnelle (choux)", "Wedding cake à l'américaine", "Naked cake", "Macaron tower", "Dessert buffet", "Pas de gâteau spécial", "Autre"],
    impactsPricing: true,
    pricingNote: "Pièce montée = 3-15€/part, wedding cake = 8-25€/part",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-017",
    text: "Quel style / thème / palette de couleurs souhaitez-vous ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Thème élaboré = plus de décoration, scénographie, accessoires",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-018",
    text: "Quels éléments de décoration souhaitez-vous ? (centres de table, arche, guirlandes, bougies, drapés, néon, etc.)",
    type: "multiselect",
    options: ["Centres de table floraux", "Arche cérémonie", "Guirlandes lumineuses", "Bougies/photophores", "Drapés/voilages", "Néon personnalisé", "Chemin de table végétal", "Lanternes", "Panneau de bienvenue", "Plan de table décoratif", "Coins lounge", "Tapis de cérémonie", "Autre"],
    impactsPricing: true,
    pricingNote: "Chaque élément de décor a un coût propre",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-019",
    text: "Quel type de fleurs souhaitez-vous ? (bouquet mariée, boutonnières, compositions tables, arche florale)",
    type: "multiselect",
    options: ["Bouquet de la mariée", "Boutonnières", "Compositions centre de table", "Arche florale", "Corsages demoiselles d'honneur", "Pétales allée", "Couronne de fleurs", "Décor voiture", "Fleurs fraîches", "Fleurs séchées", "Fleurs artificielles", "Pas de fleurs"],
    impactsPricing: true,
    pricingNote: "Fleurs = 500-5000€+ selon la saison et les variétés",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-020",
    text: "Souhaitez-vous un photographe ? (couverture complète, demi-journée, juste cérémonie, drone)",
    type: "select",
    options: ["Journée complète (préparatifs au lendemain)", "Demi-journée", "Cérémonie + cocktail uniquement", "Pas de photographe pro", "Deux photographes"],
    impactsPricing: true,
    pricingNote: "Photographe = 1000-4000€ selon la durée",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-021",
    text: "Souhaitez-vous un vidéaste / film de mariage ?",
    type: "select",
    options: ["Film complet (10-30 min)", "Teaser/clip (3-5 min)", "Captation cérémonie uniquement", "Drone uniquement", "Film + drone", "Non"],
    impactsPricing: true,
    pricingNote: "Vidéaste = 1500-5000€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-022",
    text: "Quel type de musique / animation souhaitez-vous ?",
    type: "multiselect",
    options: ["DJ", "Groupe/orchestre live", "Violoniste/musicien cérémonie", "Chanteuse gospel", "Jazz band cocktail", "Karaoké", "Silence/playlist perso", "DJ + live"],
    impactsPricing: true,
    pricingNote: "DJ = 600-2000€, orchestre live = 2000-8000€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-023",
    text: "Souhaitez-vous des animations spécifiques ? (photobooth, magicien, feu d'artifice, lâcher de lanternes, etc.)",
    type: "multiselect",
    options: ["Photobooth/cabine photo", "Magicien", "Feu d'artifice", "Fontaine à chocolat", "Candy bar", "Cigare bar", "Casino éphémère", "Karaoké", "Lâcher de lanternes", "Lâcher de colombes", "Spectacle pyrotechnique", "Caricaturiste", "Barman cocktail show", "Première danse chorégraphiée", "Autre"],
    impactsPricing: true,
    pricingNote: "Chaque animation = prestation séparée (100-3000€)",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-024",
    text: "Avez-vous besoin de transport pour les invités ? (navettes, bus, voitures anciennes)",
    type: "multiselect",
    options: ["Navette aller-retour", "Bus/minibus", "Voiture ancienne/collection pour les mariés", "Calèche", "Limousine", "Aucun besoin"],
    impactsPricing: true,
    pricingNote: "Navette = 500-2000€, voiture collection = 300-1500€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-025",
    text: "Les invités ont-ils besoin d'hébergement sur place ou à proximité ?",
    type: "select",
    options: ["Oui, hébergement sur le lieu", "Oui, hôtels à proximité à recommander", "Non, tout le monde est local"],
    impactsPricing: true,
    pricingNote: "Hébergement sur place = coût du lieu majoré, négociation bloc hôtelier",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-026",
    text: "Y aura-t-il des enfants ? Si oui, combien et quels âges ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Menu enfant, baby-sitter, animation enfants, espace dédié",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-027",
    text: "Souhaitez-vous un service de baby-sitting / espace enfants ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Baby-sitter = 15-25€/h, animation enfants = 200-600€",
    priority: "nice-to-have",
    conditionalOn: "mar-026",
    phase: "avant",
  },
  {
    id: "mar-028",
    text: "Avez-vous des invités à mobilité réduite ou avec des besoins spéciaux ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Peut influencer le choix du lieu (accessibilité) et la logistique",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-029",
    text: "Souhaitez-vous un faire-part / save the date ? (papier, digital, les deux)",
    type: "select",
    options: ["Faire-part papier", "Save the date + faire-part papier", "Invitation digitale", "Site web de mariage", "Les deux (papier + digital)", "Déjà fait"],
    impactsPricing: true,
    pricingNote: "Faire-part papier = 2-10€/unité, site web = 0-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-030",
    text: "Souhaitez-vous un wedding planner jour J uniquement, coordination partielle, ou organisation complète ?",
    type: "select",
    options: ["Organisation complète (de A à Z)", "Coordination partielle (je choisis les prestataires, vous coordonnez)", "Coordination jour J uniquement", "Conseil/coaching uniquement"],
    impactsPricing: true,
    pricingNote: "Complet = 10-15% du budget, jour J = 1500-3000€, partiel = entre les deux",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-031",
    text: "Avez-vous déjà réservé des prestataires ? Si oui, lesquels ?",
    type: "multiselect",
    options: ["Lieu", "Traiteur", "Photographe", "Vidéaste", "DJ/Musiciens", "Fleuriste", "Pâtissier", "Coiffeur/maquilleur", "Officiant", "Aucun pour l'instant"],
    impactsPricing: true,
    pricingNote: "Prestataires déjà réservés = moins de coordination nécessaire",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-032",
    text: "Souhaitez-vous un brunch ou un retour le lendemain ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Brunch lendemain = lieu supplémentaire + traiteur (15-40€/pers)",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-033",
    text: "Y a-t-il un enterrement de vie de jeune fille/garçon à organiser ?",
    type: "select",
    options: ["Oui, EVJF", "Oui, EVG", "Oui, les deux", "Non", "Déjà prévu"],
    impactsPricing: true,
    pricingNote: "EVJF/EVG = prestation séparée",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-034",
    text: "Souhaitez-vous un essai maquillage et coiffure avant le jour J ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Essai = 50-150€ par essai",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-035",
    text: "Combien de demoiselles d'honneur / témoins auront besoin de coiffure/maquillage ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Chaque personne = 80-200€ coiffure+maquillage",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-036",
    text: "Souhaitez-vous des cadeaux invités / dragées / souvenirs ?",
    type: "select",
    options: ["Dragées traditionnelles", "Cadeaux personnalisés", "Petits pots miel/confiture", "Bougies", "Graines à planter", "Rien de prévu", "Autre"],
    impactsPricing: true,
    pricingNote: "Cadeaux invités = 2-15€/pers",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-037",
    text: "Avez-vous besoin de location de mobilier supplémentaire ? (chaises, tables, vaisselle, nappes)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Location mobilier = 5-30€/pers selon le standing",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-038",
    text: "Y a-t-il un dress code pour les invités ?",
    type: "select",
    options: ["Formel/cravate noire", "Semi-formel/cocktail", "Champêtre/décontracté", "Thème couleur imposé", "Pas de dress code", "Autre"],
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-039",
    text: "Le mariage sera-t-il en intérieur, extérieur, ou les deux ?",
    type: "select",
    options: ["Intérieur uniquement", "Extérieur uniquement", "Cérémonie extérieur + réception intérieur", "Les deux en extérieur avec tente", "Flexible selon météo"],
    impactsPricing: true,
    pricingNote: "Extérieur = sonorisation, éclairage, chapiteau potentiel",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-040",
    text: "Souhaitez-vous un livre d'or, une urne, un arbre à empreintes ou autre système de voeux ?",
    type: "multiselect",
    options: ["Livre d'or classique", "Arbre à empreintes", "Urne", "Vidéo messages", "Polaroid + messages", "Rien"],
    impactsPricing: true,
    pricingNote: "Accessoires = 20-200€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-041",
    text: "Partez-vous en lune de miel directement après ? (impact sur le timing de fin)",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-042",
    text: "Y a-t-il des contraintes horaires à respecter ? (couvre-feu lieu, heure mairie, etc.)",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Couvre-feu peut nécessiter une after-party ailleurs",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-043",
    text: "Souhaitez-vous un éclairage décoratif spécial ? (guirlandes, uplighting, projecteurs, lasers)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Éclairage événementiel = 300-3000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-044",
    text: "Avez-vous besoin d'une sonorisation pour la cérémonie ? (micro, enceintes)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Sono cérémonie = 200-800€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "mar-045",
    text: "Des invités viennent-ils de l'étranger ? Nécessitent-ils une assistance particulière ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Traduction, transferts aéroport, hébergement prolongé",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "mar-046",
    text: "À quelle heure souhaitez-vous que la journée commence ? (préparatifs)",
    type: "time",
    impactsPricing: true,
    pricingNote: "Démarrage tôt = plus d'heures de prestation",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-047",
    text: "À quelle heure souhaitez-vous que la fête se termine ?",
    type: "time",
    impactsPricing: true,
    pricingNote: "Après minuit = supplément DJ, lieu, sécurité",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-048",
    text: "Y aura-t-il des discours / speeches ? Combien et à quel moment ?",
    type: "textarea",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-049",
    text: "Souhaitez-vous une première danse ? Avec chorégraphie préparée ?",
    type: "select",
    options: ["Oui, spontanée", "Oui, chorégraphiée", "Non"],
    impactsPricing: true,
    pricingNote: "Chorégraphie = cours de danse (200-600€)",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-050",
    text: "Prévoyez-vous une ouverture de bal traditionnelle (valse, etc.) ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-051",
    text: "Avez-vous besoin d'un coordinateur/régisseur sur place le jour J ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Coordinateur jour J = 800-2000€",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-052",
    text: "Y a-t-il un moment prévu pour le lancer de bouquet ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "mar-053",
    text: "Souhaitez-vous un late-night snack / food truck en fin de soirée ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Late night food = 5-15€/pers",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "mar-054",
    text: "Souhaitez-vous recevoir un album photo professionnel ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Album = 300-1000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "mar-055",
    text: "Souhaitez-vous des cartes de remerciement ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Cartes remerciement = 1-5€/unité",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "mar-056",
    text: "Qui se charge du nettoyage et du rangement du lieu ?",
    type: "select",
    options: ["Nous-mêmes / famille", "Inclus dans la location du lieu", "Je souhaite une prestation de nettoyage", "Je ne sais pas"],
    impactsPricing: true,
    pricingNote: "Nettoyage pro = 200-800€ selon la surface",
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 2. ANNIVERSAIRE (Birthday)
// =============================================================================
export const ANNIVERSAIRE_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "ann-001",
    text: "Quel âge fête-t-on ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Anniversaire chiffre rond (18, 30, 40, 50, 60) = souvent plus ambitieux",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-002",
    text: "Est-ce un anniversaire enfant (1-12), ado (13-17), ou adulte (18+) ?",
    type: "select",
    options: ["Enfant (1-12 ans)", "Adolescent (13-17 ans)", "Jeune adulte (18-30)", "Adulte (30-60)", "Senior (60+)"],
    impactsPricing: true,
    pricingNote: "Type de prestation totalement différent selon la tranche d'âge",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-003",
    text: "Quelle est la date souhaitée ?",
    type: "date",
    impactsPricing: true,
    pricingNote: "Week-end et jours fériés = tarifs majorés",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-004",
    text: "Combien d'invités prévoyez-vous ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Impact direct sur lieu, traiteur, animations",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-005",
    text: "Quel est votre budget global ?",
    type: "select",
    options: ["Moins de 500€", "500-1 000€", "1 000-3 000€", "3 000-5 000€", "5 000-10 000€", "Plus de 10 000€"],
    impactsPricing: true,
    pricingNote: "Détermine le niveau de prestation",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-006",
    text: "Y a-t-il un thème pour la fête ? (super-héros, princesse, année 80, tropical, casino, etc.)",
    type: "text",
    impactsPricing: true,
    pricingNote: "Thème = décor spécifique, costumes, accessoires",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-007",
    text: "Où souhaitez-vous organiser la fête ? (domicile, salle, restaurant, parc, lieu insolite)",
    type: "select",
    options: ["À domicile", "Salle des fêtes", "Restaurant/bar privatisé", "Parc/jardin", "Lieu insolite (escape game, bowling, karting, etc.)", "Discothèque/club", "Plein air/plage", "Autre"],
    impactsPricing: true,
    pricingNote: "Location salle = 200-2000€, restaurant privatisé = minimum de dépense",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-008",
    text: "Quel type de restauration souhaitez-vous ?",
    type: "select",
    options: ["Gâteau + bonbons uniquement", "Goûter complet (enfant)", "Apéritif dînatoire", "Buffet", "Repas assis", "Food truck", "Barbecue", "Brunch"],
    impactsPricing: true,
    pricingNote: "Impact majeur sur le budget",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-009",
    text: "Quel type de gâteau souhaitez-vous ? (nombre de parts, design, goût, cake design, pièce montée)",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Gâteau personnalisé cake design = 5-15€/part",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-010",
    text: "Y a-t-il des allergies ou régimes alimentaires à prendre en compte ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Menus spéciaux = surcoût traiteur",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-011",
    text: "Souhaitez-vous des boissons alcoolisées ? (open bar, champagne, cocktails)",
    type: "select",
    options: ["Non (anniversaire enfant)", "Oui, open bar", "Oui, champagne pour le toast", "Oui, cocktails signature", "Oui, bar à bières/vins", "Soft uniquement"],
    impactsPricing: true,
    pricingNote: "Alcool = poste variable important",
    priority: "essential",
    conditionalOn: "ann-002",
    phase: "avant",
  },
  {
    id: "ann-012",
    text: "Quelles animations souhaitez-vous ?",
    type: "multiselect",
    options: [
      "DJ", "Groupe live", "Karaoké", "Photobooth",
      "Magicien", "Clown (enfant)", "Maquillage artistique (enfant)",
      "Sculpteur de ballons (enfant)", "Château gonflable (enfant)",
      "Chasse au trésor", "Escape game", "Casino", "Quiz/blind test",
      "Danseurs", "Spectacle de feu", "Atelier créatif",
      "Jeux vidéo/VR", "Karting", "Paintball", "Laser game",
      "Aucune animation particulière"
    ],
    impactsPricing: true,
    pricingNote: "Chaque animation = 100-2000€ selon le type",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-013",
    text: "Est-ce une fête surprise ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Surprise = coordination supplémentaire, logistique cachée",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-014",
    text: "Si surprise, qui est le contact principal pour l'organisation ?",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: "ann-013",
    phase: "avant",
  },
  {
    id: "ann-015",
    text: "Souhaitez-vous un photobooth / borne photo ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Photobooth = 300-800€ (location + accessoires)",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-016",
    text: "Souhaitez-vous des décorations spécifiques ? (ballons, bannières, décor de table, candy bar)",
    type: "multiselect",
    options: ["Arche de ballons", "Ballons hélium", "Bannière personnalisée", "Décor de table thématique", "Candy bar", "Piñata", "Confettis/serpentins", "Guirlandes", "Décor lumineux", "Rien de spécial"],
    impactsPricing: true,
    pricingNote: "Décoration = 100-2000€ selon l'ambition",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-017",
    text: "Y aura-t-il des enfants présents ? Si oui, combien et quels âges ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Espace enfants, animation, menu enfant",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-018",
    text: "Souhaitez-vous envoyer des invitations ? (papier, digitales, WhatsApp)",
    type: "select",
    options: ["Invitations papier", "Invitation digitale / e-mail", "WhatsApp/SMS", "Événement Facebook", "Pas besoin"],
    impactsPricing: true,
    pricingNote: "Invitations papier = 1-5€/unité",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-019",
    text: "Souhaitez-vous un dress code ?",
    type: "text",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-020",
    text: "Y a-t-il un cadeau groupé / cagnotte prévue ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-021",
    text: "Souhaitez-vous un diaporama / vidéo souvenir projeté pendant la fête ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Montage vidéo = 200-800€, matériel projection = 100-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-022",
    text: "Horaires souhaités pour la fête ? (début et fin)",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Durée = coût du lieu, DJ, animations",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-023",
    text: "Souhaitez-vous des sachets/sacs de cadeaux pour les invités (surtout enfants) ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Sachets cadeaux = 3-10€/enfant",
    priority: "nice-to-have",
    conditionalOn: "ann-002",
    phase: "avant",
  },
  {
    id: "ann-024",
    text: "Avez-vous besoin de matériel son/lumière ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Sono + éclairage = 200-1500€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "ann-025",
    text: "La personne fêtée a-t-elle des passions, hobbies ou centres d'intérêt à intégrer dans le thème ?",
    type: "textarea",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "ann-026",
    text: "Comment souhaitez-vous le moment du gâteau ? (bougies, chanson, surprise, feu de Bengale)",
    type: "textarea",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "ann-027",
    text: "Y aura-t-il des discours ou des jeux organisés ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "ann-028",
    text: "Souhaitez-vous un coordinateur sur place le jour de la fête ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Coordinateur = 500-1500€ selon la durée",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "ann-029",
    text: "Souhaitez-vous un photographe ou récupérer les photos des invités ?",
    type: "select",
    options: ["Photographe professionnel", "Album collaboratif (QR code/app)", "Pas besoin"],
    impactsPricing: true,
    pricingNote: "Photographe 3-4h = 400-1200€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "ann-030",
    text: "Qui se charge du nettoyage après la fête ?",
    type: "select",
    options: ["Nous-mêmes", "Inclus dans la location", "Prestation de nettoyage souhaitée"],
    impactsPricing: true,
    pricingNote: "Nettoyage = 100-500€",
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 3. BAPTEME (Baptism/Christening)
// =============================================================================
export const BAPTEME_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "bap-001",
    text: "S'agit-il d'un baptême religieux ou civil (républicain) ?",
    type: "select",
    options: ["Religieux catholique", "Religieux protestant", "Religieux orthodoxe", "Civil / républicain", "Mixte"],
    impactsPricing: true,
    pricingNote: "Baptême religieux = coordination avec la paroisse, cérémonie spécifique",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-002",
    text: "Quel est l'âge de l'enfant (ou de la personne) baptisé(e) ?",
    type: "text",
    impactsPricing: true,
    pricingNote: "Bébé = horaires adaptés aux siestes, enfant/adulte = déroulement différent",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-003",
    text: "Quelle est la date de la cérémonie ?",
    type: "date",
    impactsPricing: true,
    pricingNote: "Saison = impact sur lieu et tarifs",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-004",
    text: "À quelle heure est la cérémonie religieuse/civile ?",
    type: "time",
    impactsPricing: true,
    pricingNote: "Heure de cérémonie = détermine si réception = déjeuner ou goûter",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-005",
    text: "Combien d'invités attendez-vous ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Impact direct sur traiteur, lieu, dragées",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-006",
    text: "Quel est votre budget global ?",
    type: "select",
    options: ["Moins de 500€", "500-1 500€", "1 500-3 000€", "3 000-5 000€", "5 000-10 000€", "Plus de 10 000€"],
    impactsPricing: true,
    pricingNote: "Détermine le niveau de prestation",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-007",
    text: "Où souhaitez-vous la réception après la cérémonie ? (domicile, restaurant, salle, jardin)",
    type: "select",
    options: ["À domicile", "Restaurant", "Salle de réception", "Jardin/plein air", "Domaine/château", "Salle paroissiale", "Autre"],
    impactsPricing: true,
    pricingNote: "Lieu = poste principal du budget",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-008",
    text: "Quel type de réception ? (déjeuner assis, brunch, cocktail, goûter)",
    type: "select",
    options: ["Déjeuner assis", "Brunch", "Cocktail dînatoire", "Goûter/apéritif", "Buffet", "Vin d'honneur uniquement"],
    impactsPricing: true,
    pricingNote: "Déjeuner assis = 40-100€/pers, goûter = 10-30€/pers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-009",
    text: "Y a-t-il des régimes alimentaires ou allergies à prendre en compte ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Menus spéciaux",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-010",
    text: "Souhaitez-vous des dragées ? Quel type et combien ?",
    type: "select",
    options: ["Dragées amandes traditionnelles", "Dragées chocolat", "Dragées personnalisées (boîte gravée)", "Alternatives modernes (bougies, savons, miel)", "Pas de dragées"],
    impactsPricing: true,
    pricingNote: "Dragées = 2-8€/boîte",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-011",
    text: "Quel thème / palette de couleurs pour la décoration ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Thème élaboré = plus de décoration",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-012",
    text: "Souhaitez-vous un gâteau spécial pour le baptême ?",
    type: "select",
    options: ["Gâteau cake design thème baptême", "Pièce montée", "Gâteau classique pâtissier", "Pas de gâteau spécial"],
    impactsPricing: true,
    pricingNote: "Cake design = 5-12€/part",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-013",
    text: "Qui sont le parrain et la marraine ? (coordination pour discours, rôle cérémonie)",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-014",
    text: "Y a-t-il des traditions familiales ou culturelles à respecter ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Traditions spécifiques peuvent nécessiter des éléments particuliers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-015",
    text: "Souhaitez-vous un photographe professionnel ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Photographe = 300-1500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-016",
    text: "Combien d'enfants seront présents ? Quels âges ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Animation enfants, espace jeux, menu enfant",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-017",
    text: "Souhaitez-vous une animation pour les enfants pendant la réception ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Animation enfants = 150-500€",
    priority: "nice-to-have",
    conditionalOn: "bap-016",
    phase: "avant",
  },
  {
    id: "bap-018",
    text: "Avez-vous besoin de faire-part / invitations pour le baptême ?",
    type: "select",
    options: ["Faire-part papier", "Invitation digitale", "Les deux", "Déjà fait"],
    impactsPricing: true,
    pricingNote: "Faire-part papier = 1-5€/unité",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-019",
    text: "Souhaitez-vous des éléments décoratifs spécifiques ? (ballons, fleurs, arche, chemin de table)",
    type: "multiselect",
    options: ["Ballons", "Compositions florales", "Arche décorative", "Chemin de table", "Guirlandes", "Bougies", "Centre de table", "Candy bar", "Panneau de bienvenue"],
    impactsPricing: true,
    pricingNote: "Décoration = 100-2000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-020",
    text: "Le lieu est-il adapté pour un bébé ? (espace change, calme pour sieste, espace allaitement)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Aménagement espace bébé si besoin",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-021",
    text: "Souhaitez-vous un livre d'or ou un arbre à souhaits ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Livre d'or/arbre = 20-100€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-022",
    text: "Y a-t-il un dress code souhaité ?",
    type: "text",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-023",
    text: "Avez-vous besoin de tenues spéciales ? (robe de baptême, tenue du parrain/marraine)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Robe de baptême = 50-300€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-024",
    text: "Des invités viennent-ils de loin ? Besoin d'hébergement/transport ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Logistique transport/hébergement",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bap-025",
    text: "Souhaitez-vous de la musique ? (playlist, musicien live, DJ)",
    type: "select",
    options: ["Playlist personnelle", "Musicien live (violon, harpe, etc.)", "DJ", "Pas de musique"],
    impactsPricing: true,
    pricingNote: "Musicien = 300-1500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "bap-026",
    text: "À quelle heure commence et se termine la réception ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Durée = coût du lieu et des prestataires",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "bap-027",
    text: "Y aura-t-il des discours du parrain/marraine ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "bap-028",
    text: "Avez-vous besoin d'un coordinateur sur place ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Coordinateur = 400-1000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "bap-029",
    text: "Souhaitez-vous des cartes de remerciement ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Cartes = 1-3€/unité",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "bap-030",
    text: "Qui se charge du nettoyage et du rangement ?",
    type: "select",
    options: ["Nous-mêmes", "Inclus dans la location", "Prestation souhaitée"],
    impactsPricing: true,
    pricingNote: "Nettoyage = 100-400€",
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 4. FIANCAILLES (Engagement Party)
// =============================================================================
export const FIANCAILLES_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "fia-001",
    text: "Est-ce une fête surprise pour l'un des deux partenaires ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Surprise = logistique secrète, coordination compliquée",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-002",
    text: "Si surprise, qui organise et qui est le contact principal ?",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: "fia-001",
    phase: "avant",
  },
  {
    id: "fia-003",
    text: "La demande en mariage a-t-elle déjà eu lieu ou souhaitez-vous qu'elle ait lieu pendant la fête ?",
    type: "select",
    options: ["Déjà faite, c'est une célébration", "La demande aura lieu pendant la fête", "C'est la fête de fiançailles officielle (après la demande)"],
    impactsPricing: true,
    pricingNote: "Demande pendant la fête = mise en scène spéciale (photographe caché, décor surprise)",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-004",
    text: "Quelle est la date souhaitée ?",
    type: "date",
    impactsPricing: true,
    pricingNote: "Saison et jour de la semaine",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-005",
    text: "Combien d'invités prévoyez-vous ?",
    type: "select",
    options: ["Intime (2-10)", "Petit comité (10-30)", "Moyen (30-60)", "Grand (60-100)", "Très grand (100+)"],
    impactsPricing: true,
    pricingNote: "Impact sur lieu, traiteur",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-006",
    text: "Quel est votre budget ?",
    type: "select",
    options: ["Moins de 500€", "500-1 500€", "1 500-3 000€", "3 000-5 000€", "5 000-10 000€", "Plus de 10 000€"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-007",
    text: "Quel type de fête souhaitez-vous ? (dîner intime, cocktail, garden party, brunch)",
    type: "select",
    options: ["Dîner intime", "Cocktail/apéritif", "Garden party", "Brunch", "Soirée dansante", "Pique-nique chic", "Autre"],
    impactsPricing: true,
    pricingNote: "Format = détermine le budget global",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-008",
    text: "Où souhaitez-vous organiser la fête ?",
    type: "select",
    options: ["Domicile", "Restaurant privatisé", "Bar/lounge", "Jardin privé", "Rooftop", "Salle de réception", "Lieu insolite", "Autre"],
    impactsPricing: true,
    pricingNote: "Lieu = poste principal",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-009",
    text: "Souhaitez-vous un moment spécial pour montrer la bague / célébrer la demande ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Mise en scène = éclairage, photographe, musique spéciale",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-010",
    text: "Souhaitez-vous du champagne ou un toast spécial ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Champagne = 20-60€/bouteille",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-011",
    text: "Quel type de restauration ?",
    type: "select",
    options: ["Apéritif/cocktail", "Dîner assis", "Buffet", "Brunch", "Desserts uniquement"],
    impactsPricing: true,
    pricingNote: "Dîner assis = 40-100€/pers, cocktail = 20-50€/pers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-012",
    text: "Y a-t-il des régimes alimentaires ou allergies ?",
    type: "textarea",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-013",
    text: "Souhaitez-vous un thème ou une palette de couleurs ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Thème = décor spécifique",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-014",
    text: "Souhaitez-vous de la décoration ? (fleurs, ballons, bougies, panneau 'She said yes')",
    type: "multiselect",
    options: ["Fleurs", "Ballons", "Bougies", "Panneau/néon personnalisé", "Guirlandes lumineuses", "Photos du couple", "Rien de spécial"],
    impactsPricing: true,
    pricingNote: "Décoration = 100-1500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-015",
    text: "Souhaitez-vous un photographe ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Photographe 2-3h = 300-800€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-016",
    text: "Souhaitez-vous de la musique ? (playlist, DJ, musicien live)",
    type: "select",
    options: ["Playlist perso", "DJ", "Musicien live", "Pas de musique"],
    impactsPricing: true,
    pricingNote: "DJ = 400-1200€, musicien = 300-1000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-017",
    text: "Y a-t-il des discours ou toasts prévus ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-018",
    text: "Souhaitez-vous un gâteau spécial fiançailles ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Gâteau = 50-400€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-019",
    text: "Souhaitez-vous envoyer des invitations formelles ?",
    type: "select",
    options: ["Invitations papier", "Digitales", "WhatsApp/SMS", "Pas besoin"],
    impactsPricing: true,
    pricingNote: "Invitations papier = 1-5€/unité",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-020",
    text: "Souhaitez-vous un cadre particulier pour le couple ? (panneau photo, backdrop, etc.)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Backdrop/mur floral = 200-1000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "fia-021",
    text: "Les familles des deux côtés se connaissent-elles ? (impacte l'animation/ice-breakers)",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "fia-022",
    text: "Horaires souhaités ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Durée = coût prestataires",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "fia-023",
    text: "Souhaitez-vous un moment surprise (vidéo, diaporama, chanson) ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Montage vidéo = 200-600€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "fia-024",
    text: "Souhaitez-vous des photos/vidéos éditées après l'événement ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Édition = inclus ou 200-500€ en sus",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "fia-025",
    text: "Nettoyage et rangement du lieu ?",
    type: "select",
    options: ["Nous-mêmes", "Inclus", "Prestation souhaitée"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 5. BABY SHOWER
// =============================================================================
export const BABY_SHOWER_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "bs-001",
    text: "La future maman est-elle au courant ou est-ce une surprise ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Surprise = coordination secrète",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-002",
    text: "Si surprise, qui est le contact organisateur ?",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: "bs-001",
    phase: "avant",
  },
  {
    id: "bs-003",
    text: "À quel mois de grossesse sera la future maman le jour de l'événement ?",
    type: "number",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-004",
    text: "Connaît-on le sexe du bébé ? Souhaitez-vous intégrer un gender reveal ?",
    type: "select",
    options: ["Oui, c'est une fille", "Oui, c'est un garçon", "Non, le sexe n'est pas connu", "Gender reveal pendant la baby shower", "On ne souhaite pas révéler le sexe"],
    impactsPricing: true,
    pricingNote: "Gender reveal = mise en scène spéciale (ballon, gâteau, fumigène) 50-300€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-005",
    text: "Quelle est la date souhaitée ?",
    type: "date",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-006",
    text: "Combien d'invités ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Impact sur lieu, nourriture, activités",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-007",
    text: "Quel est le budget ?",
    type: "select",
    options: ["Moins de 300€", "300-500€", "500-1 000€", "1 000-2 000€", "2 000-5 000€", "Plus de 5 000€"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-008",
    text: "Y a-t-il un thème ? (ourson, nuages, safari, bohème, floral, princesse, etc.)",
    type: "text",
    impactsPricing: true,
    pricingNote: "Thème = décoration spécifique",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-009",
    text: "Palette de couleurs souhaitée ?",
    type: "text",
    impactsPricing: true,
    pricingNote: "Couleurs = choix de la décoration, ballons, vaisselle",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-010",
    text: "Où souhaitez-vous organiser ? (domicile, restaurant, salle, jardin, spa)",
    type: "select",
    options: ["À domicile", "Restaurant/salon de thé", "Salle louée", "Jardin/terrasse", "Spa/bien-être", "Atelier créatif", "Autre"],
    impactsPricing: true,
    pricingNote: "Lieu = poste variable",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-011",
    text: "Quel type de restauration ? (brunch, goûter sucré, apéritif, buffet)",
    type: "select",
    options: ["Brunch", "Goûter sucré (gâteaux, cupcakes, macarons)", "Apéritif/cocktail", "Buffet sucré-salé", "Autre"],
    impactsPricing: true,
    pricingNote: "Traiteur/pâtissier",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-012",
    text: "La future maman a-t-elle des restrictions alimentaires liées à la grossesse ou des allergies ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Menu adapté grossesse (pas de cru, certains fromages, etc.)",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-013",
    text: "Souhaitez-vous un gâteau spécial baby shower ? (cake design, cupcakes, cake pops)",
    type: "select",
    options: ["Gâteau cake design", "Cupcakes assortis", "Cake pops", "Gâteau classique", "Pas de gâteau spécial"],
    impactsPricing: true,
    pricingNote: "Cake design = 4-12€/part",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-014",
    text: "Souhaitez-vous des boissons spéciales ? (cocktails sans alcool, bar à smoothies, thé/café)",
    type: "multiselect",
    options: ["Cocktails sans alcool (mocktails)", "Cocktails avec alcool", "Bar à smoothies", "Thé/café/chocolat chaud", "Limonade artisanale", "Champagne pour le toast"],
    impactsPricing: true,
    pricingNote: "Bar à cocktails = 200-600€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-015",
    text: "Quelles activités/jeux souhaitez-vous ?",
    type: "multiselect",
    options: [
      "Deviner la taille du ventre", "Blind test comptines",
      "Baby bingo", "Décoration de bodys/bavoirs",
      "Message au bébé (livre d'or)", "Pronostics bébé (poids, date, prénom)",
      "Quiz sur les parents", "Atelier création (couronnes de fleurs, etc.)",
      "Deviner les aliments bébé", "Course de biberons",
      "Pas de jeux"
    ],
    impactsPricing: true,
    pricingNote: "Activités créatives = matériel 50-200€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-016",
    text: "Y a-t-il une liste de naissance / gift registry ? Souhaitez-vous l'intégrer ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-017",
    text: "Souhaitez-vous des décorations spécifiques ?",
    type: "multiselect",
    options: ["Arche de ballons", "Guirlande prénom bébé", "Table décorée (sweet table)", "Bannière 'Baby Shower'", "Fleurs", "Lanternes/bougies", "Pliage serviettes", "Décor mural", "Rien de spécial"],
    impactsPricing: true,
    pricingNote: "Décoration = 50-1000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-018",
    text: "Souhaitez-vous un photographe ou une borne photo ?",
    type: "select",
    options: ["Photographe pro", "Borne photo/photobooth", "Les deux", "Pas besoin"],
    impactsPricing: true,
    pricingNote: "Photographe = 200-600€, borne = 200-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-019",
    text: "Y aura-t-il des enfants/bébés des invitées ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Espace enfants, animation",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-020",
    text: "Souhaitez-vous des petits cadeaux pour les invités (remerciements) ?",
    type: "select",
    options: ["Petits savons", "Bougies", "Sucettes/bonbons", "Sachets de thé", "Mini plantes", "Rien"],
    impactsPricing: true,
    pricingNote: "Cadeaux invités = 2-8€/pers",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-021",
    text: "La baby shower est-elle mixte (avec les futurs papas et hommes) ou entre femmes ?",
    type: "select",
    options: ["Entre femmes uniquement", "Mixte (hommes et femmes)", "Baby shower + BBQ pour les hommes séparé"],
    impactsPricing: true,
    pricingNote: "Mixte = plus d'invités, activités différentes",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-022",
    text: "Souhaitez-vous des invitations ? (papier, digitales)",
    type: "select",
    options: ["Papier", "Digitales", "WhatsApp", "Pas besoin"],
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "bs-023",
    text: "Y a-t-il un dress code ?",
    type: "text",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "bs-024",
    text: "Horaires souhaités ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Durée de la prestation",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "bs-025",
    text: "À quel moment souhaitez-vous l'ouverture des cadeaux ?",
    type: "select",
    options: ["Pendant la fête, en groupe", "À la fin", "En privé après la fête", "Pas d'ouverture de cadeaux"],
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "bs-026",
    text: "Avez-vous besoin d'un coordinateur sur place ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Coordinateur = 300-800€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "bs-027",
    text: "Souhaitez-vous des photos éditées après l'événement ?",
    type: "boolean",
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "bs-028",
    text: "Nettoyage du lieu ?",
    type: "select",
    options: ["Nous-mêmes", "Inclus", "Prestation souhaitée"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 6. SEMINAIRE / CE (Corporate Event)
// =============================================================================
export const SEMINAIRE_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "sem-001",
    text: "Quel est le type d'événement corporate ? (séminaire, team building, soirée CE, conférence, lancement produit, afterwork, gala)",
    type: "select",
    options: ["Séminaire d'entreprise", "Team building", "Soirée comité d'entreprise (CE/CSE)", "Conférence/convention", "Lancement de produit", "Afterwork", "Gala/soirée de fin d'année", "Journée d'intégration", "Incentive/récompense", "Formation", "Salon/exposition"],
    impactsPricing: true,
    pricingNote: "Chaque format a des besoins et budgets très différents",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-002",
    text: "Quel est l'objectif principal de l'événement ?",
    type: "multiselect",
    options: ["Cohésion d'équipe", "Communication interne", "Formation/montée en compétences", "Lancement produit/service", "Récompense/motivation", "Networking", "Célébration (fin d'année, résultats)", "Brainstorming/innovation", "Intégration nouveaux collaborateurs"],
    impactsPricing: true,
    pricingNote: "L'objectif détermine le format et les activités",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-003",
    text: "Quelle est la date ou la période souhaitée ?",
    type: "date",
    impactsPricing: true,
    pricingNote: "Haute saison corpo (sept-nov, jan-mars) = tarifs majorés",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-004",
    text: "Durée de l'événement ? (demi-journée, journée, soirée, multi-jours)",
    type: "select",
    options: ["Demi-journée (3-4h)", "Journée complète", "Soirée uniquement", "2 jours / 1 nuit", "3 jours / 2 nuits", "Plus de 3 jours"],
    impactsPricing: true,
    pricingNote: "Multi-jours = hébergement, restauration x jours, transport",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-005",
    text: "Combien de participants ?",
    type: "number",
    impactsPricing: true,
    pricingNote: "Impact direct sur tous les postes",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-006",
    text: "Quel est le budget global (HT) ?",
    type: "select",
    options: ["Moins de 2 000€", "2 000-5 000€", "5 000-10 000€", "10 000-20 000€", "20 000-50 000€", "50 000-100 000€", "Plus de 100 000€"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-007",
    text: "Le budget a-t-il déjà été validé par la direction / les achats ?",
    type: "select",
    options: ["Oui, validé", "En cours de validation", "Budget estimatif, à valider après devis", "Pas encore discuté"],
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-008",
    text: "Qui est le décisionnaire final ? (DG, DRH, CE/CSE, manager)",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-009",
    text: "Quel type de lieu souhaitez-vous ?",
    type: "multiselect",
    options: ["Salle de séminaire/conférence", "Hôtel avec salles", "Domaine/château", "Espace atypique/loft", "Restaurant privatisé", "Plein air/nature", "Centre de loisirs (accrobranche, etc.)", "Bateau/croisière", "À l'étranger", "Dans les locaux de l'entreprise"],
    impactsPricing: true,
    pricingNote: "Lieu = 20-50% du budget corpo",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-010",
    text: "Dans quelle zone géographique ? (ville, rayon km, région)",
    type: "text",
    impactsPricing: true,
    pricingNote: "Paris vs province = écart de prix significatif",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-011",
    text: "Avez-vous besoin de salles de sous-commission / breakout rooms ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Salles supplémentaires = surcoût lieu",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-012",
    text: "Quels besoins en audiovisuel et technique ? (vidéoprojecteur, écrans, sono, micro, visioconférence, live streaming)",
    type: "multiselect",
    options: ["Vidéoprojecteur + écran", "Sono/microphones", "Éclairage scénique", "Visioconférence (participants à distance)", "Live streaming", "Captation vidéo", "Écrans LED", "Prompteur", "Interprétation simultanée", "WiFi haut débit", "Rien de spécial"],
    impactsPricing: true,
    pricingNote: "AV = 500-10 000€+ selon les besoins",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-013",
    text: "Y a-t-il des intervenants externes / conférenciers ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Conférenciers = 500-15 000€ selon la notoriété",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-014",
    text: "Quelles activités team building souhaitez-vous ?",
    type: "multiselect",
    options: [
      "Escape game", "Course d'orientation", "Rallye urbain",
      "Atelier cuisine/oenologie", "Karting/quad", "Accrobranche",
      "Olympiades", "Murder party", "Atelier créatif",
      "Improvisation théâtrale", "Challenge sportif",
      "Atelier RSE/solidaire", "Construction (radeau, pont, etc.)",
      "Réalité virtuelle", "Laser game/paintball",
      "Yoga/méditation/bien-être", "Pas d'activité team building"
    ],
    impactsPricing: true,
    pricingNote: "Team building = 30-150€/pers selon l'activité",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-015",
    text: "Quel type de restauration ?",
    type: "multiselect",
    options: ["Petit-déjeuner/accueil café", "Pause café/viennoiseries", "Déjeuner assis", "Buffet déjeuner", "Cocktail dînatoire", "Dîner de gala", "Food trucks", "Apéritif/afterwork"],
    impactsPricing: true,
    pricingNote: "Traiteur corpo = 30-150€/pers/repas",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-016",
    text: "Y a-t-il des régimes alimentaires à prendre en compte ? (halal, casher, végétarien, vegan, allergies)",
    type: "textarea",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-017",
    text: "Souhaitez-vous un open bar / boissons alcoolisées ?",
    type: "select",
    options: ["Oui, open bar", "Oui, vin/bière au repas", "Champagne pour le toast", "Soft uniquement", "Selon le budget"],
    impactsPricing: true,
    pricingNote: "Open bar corpo = 20-50€/pers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-018",
    text: "Les participants ont-ils besoin d'hébergement ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Hébergement = 80-200€/nuit/pers",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-019",
    text: "Avez-vous besoin d'organiser le transport des participants ? (bus, navettes, covoiturage)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Transport groupe = 500-3000€",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-020",
    text: "Y a-t-il des besoins en branding / signalétique ? (kakémonos, goodies, badges, tote bags)",
    type: "multiselect",
    options: ["Kakémonos/roll-ups", "Badges nominatifs", "Tote bags/goodies", "Signalétique directionnelle", "Photocall/backdrop brandé", "Programmes imprimés", "Rien"],
    impactsPricing: true,
    pricingNote: "Branding/goodies = 5-30€/pers",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-021",
    text: "Souhaitez-vous un photographe / vidéaste pour l'événement ?",
    type: "select",
    options: ["Photographe", "Vidéaste", "Les deux", "Non"],
    impactsPricing: true,
    pricingNote: "Photographe corpo = 600-2000€/jour",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-022",
    text: "Souhaitez-vous une animation musicale ou un spectacle ? (DJ, groupe, humoriste, magicien)",
    type: "multiselect",
    options: ["DJ", "Groupe/orchestre", "Humoriste/one-man-show", "Magicien close-up", "Spectacle (danseurs, acrobates)", "Karaoké", "Casino éphémère", "Rien"],
    impactsPricing: true,
    pricingNote: "Animation soirée = 500-5000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-023",
    text: "Y a-t-il des contraintes de confidentialité / sécurité ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Sécurité = vigiles, accès contrôlé, NDA",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-024",
    text: "Y a-t-il des personnes à mobilité réduite ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Accessibilité PMR peut limiter les choix de lieu",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-025",
    text: "Souhaitez-vous une décoration thématique / scénographie ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Scénographie corpo = 500-10 000€+",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-026",
    text: "Avez-vous besoin d'une assurance événementielle ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Assurance = 100-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-027",
    text: "L'événement nécessite-t-il des autorisations spéciales ? (occupation espace public, bruit, etc.)",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Démarches administratives = temps et frais",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-028",
    text: "Souhaitez-vous intégrer une dimension RSE / éco-responsable ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Traiteur bio/local, goodies éco, compensation carbone",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-029",
    text: "Avez-vous une charte graphique à respecter pour tous les supports ?",
    type: "boolean",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "sem-030",
    text: "Quel est le processus de facturation ? (devis, bon de commande, délai de paiement)",
    type: "textarea",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "sem-031",
    text: "Horaires précis de l'événement ? (accueil, début, pauses, fin)",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Durée totale = impact sur tous les prestataires",
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "sem-032",
    text: "Y a-t-il un programme/agenda à respecter ?",
    type: "textarea",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "sem-033",
    text: "Avez-vous besoin d'un maître de cérémonie / animateur ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "MC/animateur = 500-2000€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "sem-034",
    text: "Avez-vous besoin de personnel d'accueil / hôtesses ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Hôtesses = 150-250€/jour/personne",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "sem-035",
    text: "Souhaitez-vous un système d'inscription / émargement digital ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Plateforme inscription = 0-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "sem-036",
    text: "Souhaitez-vous un bilan post-événement avec KPIs ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Rapport post-event = inclus ou 200-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "sem-037",
    text: "Souhaitez-vous un questionnaire de satisfaction participants ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "sem-038",
    text: "Souhaitez-vous recevoir les photos/vidéos éditées ? Dans quel délai ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Montage rapide = supplément",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "sem-039",
    text: "Nettoyage et remise en état du lieu ?",
    type: "select",
    options: ["Inclus dans la location", "Prestation souhaitée", "On s'en charge"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// 7. AUTRE (Retirement, Graduation, Garden Party, etc.)
// =============================================================================
export const AUTRE_QUESTIONS: Question[] = [
  // ── AVANT ─────────────────────────────────────────────────────────────
  {
    id: "aut-001",
    text: "Quel type d'événement souhaitez-vous organiser ?",
    type: "select",
    options: ["Départ à la retraite", "Remise de diplôme / graduation", "Garden party", "Pendaison de crémaillère", "Communion", "Bar/Bat Mitzvah", "Anniversaire de mariage (noces)", "Fête de fin d'année", "Soirée à thème", "Réunion de famille", "Pot de départ", "Autre"],
    impactsPricing: true,
    pricingNote: "Le type d'événement détermine le format et le budget",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-002",
    text: "Quelle est la date souhaitée ?",
    type: "date",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-003",
    text: "Combien d'invités prévoyez-vous ?",
    type: "number",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-004",
    text: "Quel est votre budget ?",
    type: "select",
    options: ["Moins de 500€", "500-1 500€", "1 500-3 000€", "3 000-5 000€", "5 000-10 000€", "Plus de 10 000€"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-005",
    text: "Où souhaitez-vous organiser l'événement ?",
    type: "select",
    options: ["À domicile", "Restaurant", "Salle de réception", "Jardin/plein air", "Lieu insolite", "Autre"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-006",
    text: "Est-ce une fête surprise ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Surprise = coordination supplémentaire",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-007",
    text: "Si surprise, qui est le contact principal ?",
    type: "text",
    impactsPricing: false,
    priority: "essential",
    conditionalOn: "aut-006",
    phase: "avant",
  },
  {
    id: "aut-008",
    text: "Y a-t-il un thème ou une ambiance souhaitée ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Thème = décoration spécifique",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-009",
    text: "Quel type de restauration ?",
    type: "select",
    options: ["Apéritif/cocktail", "Buffet", "Repas assis", "Barbecue", "Brunch", "Goûter", "Food truck", "Traiteur complet"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-010",
    text: "Y a-t-il des régimes alimentaires ou allergies ?",
    type: "textarea",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-011",
    text: "Souhaitez-vous des boissons alcoolisées ?",
    type: "select",
    options: ["Oui, open bar", "Oui, vin/champagne", "Soft uniquement", "Selon le budget"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-012",
    text: "Souhaitez-vous un gâteau spécial ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Gâteau personnalisé = 50-500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-013",
    text: "Quelles animations souhaitez-vous ?",
    type: "multiselect",
    options: ["DJ", "Musicien live", "Karaoké", "Photobooth", "Jeux", "Diaporama/vidéo souvenir", "Discours/hommages", "Spectacle", "Aucune"],
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-014",
    text: "Souhaitez-vous de la décoration ?",
    type: "multiselect",
    options: ["Ballons", "Fleurs", "Guirlandes", "Bannières", "Bougies", "Thème spécifique", "Rien de spécial"],
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-015",
    text: "Souhaitez-vous un photographe ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Photographe = 300-1500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-016",
    text: "Y aura-t-il des enfants ? Si oui, combien ?",
    type: "textarea",
    impactsPricing: true,
    pricingNote: "Animation/menu enfants",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-017",
    text: "Y a-t-il des personnes à mobilité réduite ?",
    type: "boolean",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-018",
    text: "Avez-vous besoin d'invitations ?",
    type: "select",
    options: ["Papier", "Digitales", "Pas besoin"],
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-019",
    text: "Souhaitez-vous un diaporama ou une vidéo souvenir projetée ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Montage vidéo = 200-800€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-020",
    text: "Souhaitez-vous un livre d'or ou un système de messages ?",
    type: "boolean",
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-021",
    text: "Y a-t-il des traditions ou rituels particuliers à respecter ?",
    type: "textarea",
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-022",
    text: "Avez-vous besoin de sonorisation / micro pour des discours ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Sono = 150-600€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-023",
    text: "Souhaitez-vous des cadeaux / souvenirs pour les invités ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Cadeaux = 2-15€/pers",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "avant",
  },
  {
    id: "aut-024",
    text: "Le lieu est-il en intérieur ou extérieur ? Plan B pluie nécessaire ?",
    type: "select",
    options: ["Intérieur", "Extérieur", "Mixte", "Extérieur avec plan B"],
    impactsPricing: true,
    pricingNote: "Tente/chapiteau de repli",
    priority: "essential",
    conditionalOn: null,
    phase: "avant",
  },

  // ── JOUR J ────────────────────────────────────────────────────────────
  {
    id: "aut-025",
    text: "Horaires de début et de fin ?",
    type: "textarea",
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "aut-026",
    text: "Y aura-t-il des discours ou des moments formels ?",
    type: "boolean",
    impactsPricing: false,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },
  {
    id: "aut-027",
    text: "Avez-vous besoin d'un coordinateur sur place ?",
    type: "boolean",
    impactsPricing: true,
    pricingNote: "Coordinateur = 400-1500€",
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "jour-j",
  },

  // ── APRES ─────────────────────────────────────────────────────────────
  {
    id: "aut-028",
    text: "Souhaitez-vous des photos/vidéos professionnelles après l'événement ?",
    type: "boolean",
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "aut-029",
    text: "Souhaitez-vous des cartes de remerciement ?",
    type: "boolean",
    impactsPricing: true,
    priority: "nice-to-have",
    conditionalOn: null,
    phase: "apres",
  },
  {
    id: "aut-030",
    text: "Nettoyage et rangement du lieu ?",
    type: "select",
    options: ["Nous-mêmes", "Inclus", "Prestation souhaitée"],
    impactsPricing: true,
    priority: "essential",
    conditionalOn: null,
    phase: "apres",
  },
];

// =============================================================================
// EXPORT COMPLET
// =============================================================================
export const ALL_QUESTIONNAIRES: EventQuestionnaire[] = [
  { eventType: "mariage", questions: MARIAGE_QUESTIONS },
  { eventType: "anniversaire", questions: ANNIVERSAIRE_QUESTIONS },
  { eventType: "bapteme", questions: BAPTEME_QUESTIONS },
  { eventType: "fiancailles", questions: FIANCAILLES_QUESTIONS },
  { eventType: "baby_shower", questions: BABY_SHOWER_QUESTIONS },
  { eventType: "seminaire", questions: SEMINAIRE_QUESTIONS },
  { eventType: "autre", questions: AUTRE_QUESTIONS },
];

// Stats
// Mariage: 56 questions
// Anniversaire: 30 questions
// Baptême: 30 questions
// Fiançailles: 25 questions
// Baby Shower: 28 questions
// Séminaire/CE: 39 questions
// Autre: 30 questions
// TOTAL: 238 questions
